title: ATSG
description: A collection of resources for the ATSG community
theme: just-the-docs

url: https://github.com/Dave811/ATSG

aux_links:
  ATSG Repository: https://github.com/Dave811/ATSG

color_scheme: dark
favicon_ico: "/assets/images/favicon.ico"
