baseURL = 'https://Dave811.github.io/ATSG/'
languageCode = 'en-us'
title = 'ATSG'
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-relearn"

# For search functionality
[outputs]
  home = ["HTML", "RSS", "SEARCH", "SEARCHPAGE"]

defaultContentLanguage = "en"
[languages]
  [languages.en]
	contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.de]
	contentDir = "content/de"
    languageName = "German"
    weight = 2
