name: build-marlin
permissions:
  contents: write
# trigger on tag push
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Build Artillery_Ruby
    runs-on: ubuntu-latest
    steps:
      # ------------------- Prepare -------------------
      # Clone the Marlin repo from Dave811
      - name: Check out the PR
        uses: actions/checkout@v3
        with:
          repository: Dave811/Marlin-Artillery
          # 01.05.2023 - ecfc42c705de5fb3fc103f16d6f22fc141dc90dd
          ref: "ecfc42c705de5fb3fc103f16d6f22fc141dc90dd"
          path: Marlin-Artillery
          token: ${{ secrets.DUMMY_TOKEN }}
      # Cache pip and PlatformIO
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: Marlin-Artillery/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: Marlin-Artillery/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      # Install Python 3.7 and PlatformIO
      - name: Select Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.7" # Version range or exact version of a Python version to use, using semvers version range syntax.
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified

      # Clone the BigTreeTech TouchScreen repo
      - name: Check out BigTreeTech-Touchscreen
        uses: actions/checkout@v3
        with:
          repository: MirakelPrints/BIGTREETECH-TouchScreenFirmware
          # 17.10.2021 - 279a463b4088492d3a6b2b785609235e0ac7938d
          ref: "4c1f5e084cf9ad6433fafc154832a68220006c15"
          path: BigTreeTech-Touchscreen
          token: ${{ secrets.DUMMY_TOKEN }}
      # Cache pip and PlatformIO
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: BigTreeTech-Touchscreen/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: BigTreeTech-Touchscreen/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      # Setup Python and PlatformIO
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install PlatformIO
        run: |
          pip install -U platformio
          pio upgrade --dev
          pio pkg update --global
      # Clone bigtreetech TFT repo
      - name: Check out BigTreeTech-TFT
        uses: actions/checkout@v3
        with:
          repository: bigtreetech/BIGTREETECH-TouchScreenFirmware
          # 24.03.2023 - 60df3ef585757592c7686c7aa249750d314ae19a
          ref: "60df3ef585757592c7686c7aa249750d314ae19a"
          path: BigTreeTech-TFT-OLD
          token: ${{ secrets.DUMMY_TOKEN }}

      # checkout the release repo
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: repo

      # ------------------- Build Marlin -------------------
      # ------------------- AT-SW-fil-lev -------------------
      # Build the AT-SW-fil-lev-Marlin firmware
      - name: Build Artillery Ruby
        run: |
          cd Marlin-Artillery
          platformio run --environment Artillery_Ruby
      # Move the firmware to the release folder
      - name: Move firmware to release folder
        run: |
          mkdir -p release/AT-SW-fil-lev/Marlin
          cp -r Marlin-Artillery/.pio/build/Artillery_Ruby/firmware.bin release/AT-SW-fil-lev/Marlin/firmware.bin
          cp -r Marlin-Artillery/Marlin/Configuration.h release/AT-SW-fil-lev/Marlin/Configuration.h
          cp -r Marlin-Artillery/Marlin/Configuration_adv.h release/AT-SW-fil-lev/Marlin/Configuration_adv.h
      # ------------------- AT-GP-fil-lev -------------------
      # change #define X_BED_SIZE and Y_BED_SIZE  to 220
      - name: Change X_BED_SIZE and Y_BED_SIZE from 300 to 220 in Configuration.h
        run: |
          cd Marlin-Artillery
          sed -i 's/#define X_BED_SIZE 300/#define X_BED_SIZE 220/g' Marlin/Configuration.h
          sed -i 's/#define Y_BED_SIZE 300/#define Y_BED_SIZE 220/g' Marlin/Configuration.h
          sed -i 's/#define Z_MAX_POS 400/#define Z_MAX_POS 250/g' Marlin/Configuration.h
          sed -i 's/#define CUSTOM_MACHINE_NAME "Sidewinder X2"/#define CUSTOM_MACHINE_NAME "Genius Pro"/g' Marlin/Configuration.h

      # Build the AT-GP-fil-lev-Marlin firmware
      - name: Build Artillery Ruby
        run: |
          cd Marlin-Artillery
          platformio run --environment Artillery_Ruby
      # Move the firmware to the release folder
      - name: Move firmware to release folder
        run: |
          mkdir -p release/AT-GP-fil-lev/Marlin
          cp -r Marlin-Artillery/.pio/build/Artillery_Ruby/firmware.bin release/AT-GP-fil-lev/Marlin/firmware.bin
          cp -r Marlin-Artillery/Marlin/Configuration.h release/AT-GP-fil-lev/Marlin/Configuration.h
          cp -r Marlin-Artillery/Marlin/Configuration_adv.h release/AT-GP-fil-lev/Marlin/Configuration_adv.h
      # TODO add other Marlin configs and firmware
      # ------------------- Build Display -------------------
      # ------------------- AT-SW-fil-lev -------------------
      # copy and override the config.ini from the repo/config/TFT folder to the BigTreeTech-Touchscreen/mkstft28evo folder
      - name: Copy config.ini from repo/config/TFT to BigTreeTech-Touchscreen/mkstft28evo
        run: |
          rm BigTreeTech-Touchscreen/mkstft28evo/config.ini
          cp repo/config/TFT/config.ini BigTreeTech-Touchscreen/mkstft28evo/config.ini
      # change size_max:X220 Y220 Z250 in cd mkstft28evo/config.ini to size_max:X300 Y300 Z400
      - name: Change size_max to 300
        run: |
          cd BigTreeTech-Touchscreen
          sed -i 's/size_max:X220 Y220 Z250/size_max:X300 Y300 Z400/g' mkstft28evo/config.ini
      # Build the AT-SW-fil-lev-MKS_GD_TFT28_V4_0 firmware
      - name: Build BigTreeTech TouchScreen
        run: |
          cd BigTreeTech-Touchscreen
          platformio run --environment MKS_GD_TFT28_V4_0
      # Move the display firmware to the release folder
      - name: Move display firmware to release folder
        run: |
          mkdir -p release/AT-SW-fil-lev/TFT
          cp -r BigTreeTech-Touchscreen/mkstft28evo/* release/AT-SW-fil-lev/TFT/
      # ------------------- AT-GP-fil-lev -------------------
      # change size_max:x300 y300 z400 in cd mkstft28evo/config.ini to size_max:x220 y220 z250
      - name: Change size_max to 220
        run: |
          cd BigTreeTech-Touchscreen
          sed -i 's/size_max:X300 Y300 Z400/size_max:X220 Y220 Z250/g' mkstft28evo/config.ini
      # Build the AT-GP-fil-lev-MKS_GD_TFT28_V4_0 firmware
      - name: Build BigTreeTech TouchScreen
        run: |
          cd BigTreeTech-Touchscreen
          platformio run --environment MKS_GD_TFT28_V4_0
      # Move the display firmware to the release folder
      - name: Move display firmware to release folder
        run: |
          mkdir -p release/AT-GP-fil-lev/TFT
          cp -r BigTreeTech-Touchscreen/mkstft28evo/* release/AT-GP-fil-lev/TFT/
      # ------------------- Display Combo -------------------
      # use MKS_TFT28_NEW_GENIUS.27.x.bin from bigtreetech firmware old repo from the "Copy to SD Card root directory to update" folder to release and rename to MKSTFT28.bin, copy SW config from release/AT-SW-fil-lev/TFT to release/DisplayCombo/SW/01-MKS_TFT28_NEW_GENIUS.27.x.bin
      # copy the bmp and font folder from the "BigTreeTech-TFT-OLD/Copy to SD Card root directory to update/THEME_Unified Menu Material theme/TFT28" folder to "release/DisplayCombo/SW/01-MKS_TFT28_NEW_GENIUS.27.x.bin/TFT28"
      - name: Copy MKS_TFT28_NEW_GENIUS.27.x.bin to release folder
        run: |
          mkdir -p release/DisplayCombo/SW/01-MKS_TFT28_NEW_GENIUS.27.x.bin
          cp BigTreeTech-TFT-OLD/Copy\ to\ SD\ Card\ root\ directory\ to\ update/MKS_TFT28_NEW_GENIUS.27.x.bin release/DisplayCombo/SW/01-MKS_TFT28_NEW_GENIUS.27.x.bin/MKSTFT28.bin
          cp release/AT-SW-fil-lev/TFT/config.ini release/DisplayCombo/SW/01-MKS_TFT28_NEW_GENIUS.27.x.bin/config.ini
          cp -r BigTreeTech-TFT-OLD/Copy\ to\ SD\ Card\ root\ directory\ to\ update/THEME_Unified\ Menu\ Material\ theme/TFT28 release/DisplayCombo/SW/01-MKS_TFT28_NEW_GENIUS.27.x.bin/TFT28
      # use MKS_TFT28_V3.0.27.x.bin from bigtreetech firmware old repo from the "Copy to SD Card root directory to update" folder to release and rename to MKSTFT28.bin, copy SW config from release/AT-SW-fil-lev/TFT to release/DisplayCombo/SW/02-MKS_TFT28_V3.0.27.x.bin
      # copy the bmp and font folder from the "BigTreeTech-TFT-OLD/Copy to SD Card root directory to update/THEME_Unified Menu Material theme/TFT28" folder to "release/DisplayCombo/SW/02-MKS_TFT28_V3.0.27.x.bin/TFT28"
      - name: Copy MKS_TFT28_V3.0.27.x.bin to release folder
        run: |
          mkdir -p release/DisplayCombo/SW/02-MKS_TFT28_V3.0.27.x.bin
          cp BigTreeTech-TFT-OLD/Copy\ to\ SD\ Card\ root\ directory\ to\ update/MKS_TFT28_V3.0.27.x.bin release/DisplayCombo/SW/02-MKS_TFT28_V3.0.27.x.bin/MKSTFT28.bin
          cp release/AT-SW-fil-lev/TFT/config.ini release/DisplayCombo/SW/02-MKS_TFT28_V3.0.27.x.bin/config.ini
          cp -r BigTreeTech-TFT-OLD/Copy\ to\ SD\ Card\ root\ directory\ to\ update/THEME_Unified\ Menu\ Material\ theme/TFT28 release/DisplayCombo/SW/02-MKS_TFT28_V3.0.27.x.bin/TFT28
      # use MKS_TFT28_V4.0.27.x.bin from bigtreetech firmware old repo from the "Copy to SD Card root directory to update" folder to release and rename to MKSTFT28.bin, copy SW config from release/AT-SW-fil-lev/TFT to release/DisplayCombo/SW/03-MKS_TFT28_V4.0.27.x.bin
      # copy the bmp and font folder from the "BigTreeTech-TFT-OLD/Copy to SD Card root directory to update/THEME_Unified Menu Material theme/TFT28" folder to "release/DisplayCombo/SW/03-MKS_TFT28_V4.0.27.x.bin/TFT28"
      - name: Copy MKS_TFT28_V4.0.27.x.bin to release folder
        run: |
          mkdir -p release/DisplayCombo/SW/03-MKS_TFT28_V4.0.27.x.bin
          cp BigTreeTech-TFT-OLD/Copy\ to\ SD\ Card\ root\ directory\ to\ update/MKS_TFT28_V4.0.27.x.bin release/DisplayCombo/SW/03-MKS_TFT28_V4.0.27.x.bin/MKSTFT28.bin
          cp release/AT-SW-fil-lev/TFT/config.ini release/DisplayCombo/SW/03-MKS_TFT28_V4.0.27.x.bin/config.ini
          cp -r BigTreeTech-TFT-OLD/Copy\ to\ SD\ Card\ root\ directory\ to\ update/THEME_Unified\ Menu\ Material\ theme/TFT28 release/DisplayCombo/SW/03-MKS_TFT28_V4.0.27.x.bin/TFT28

      # copy the SW folder to GP folder
      - name: Copy SW folder to GP folder
        run: |
          cp -r release/DisplayCombo/SW release/DisplayCombo/GP
      # copy and replace the config.ini from release/AT-GP-fil-lev/TFT to release/DisplayCombo/GP/01-MKS_TFT28_NEW_GENIUS.27.x.bin and release/DisplayCombo/GP/02-MKS_TFT28_V3.0.27.x.bin and release/DisplayCombo/GP/03-MKS_TFT28_V4.0.27.x.bin
      - name: Copy and replace config.ini to GP folder
        run: |
          cp release/AT-GP-fil-lev/TFT/config.ini release/DisplayCombo/GP/01-MKS_TFT28_NEW_GENIUS.27.x.bin/config.ini
          cp release/AT-GP-fil-lev/TFT/config.ini release/DisplayCombo/GP/02-MKS_TFT28_V3.0.27.x.bin/config.ini
          cp release/AT-GP-fil-lev/TFT/config.ini release/DisplayCombo/GP/03-MKS_TFT28_V4.0.27.x.bin/config.ini
      # TODO add other display configs and firmware
      # ------------------- Zip Release -------------------
      # create zip file
      # ------------------- AT-SW-fil-lev -------------------
      - name: Create zip file max compression
        run: |
          cd release
          zip -r -9 AT-SW-fil-lev.zip AT-SW-fil-lev/
      # ------------------- AT-GP-fil-lev -------------------
      - name: Create zip file max compression
        run: |
          cd release
          zip -r -9 AT-GP-fil-lev.zip AT-GP-fil-lev/

      # ------------------- Display Combo -------------------
      # create zip file
      - name: Create zip file max compression
        run: |
          cd release
          zip -r -9 DisplayCombo.zip DisplayCombo/
      # ------------------- Upload Release to artifact -------------------
      - name: Upload AT-SW-fil-lev
        uses: actions/upload-artifact@v2
        with:
          name: AT-SW-fil-lev
          path: release/AT-SW-fil-lev.zip
      - name: AT-GP-fil-lev
        uses: actions/upload-artifact@v2
        with:
          name: AT-GP-fil-lev
          path: release/AT-GP-fil-lev.zip
      - name: DisplayCombo
        uses: actions/upload-artifact@v2
        with:
          name: DisplayCombo
          path: release/DisplayCombo.zip
      # ------------------- Upload Release -------------------
      - name: Upload zip file
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/AT-SW-fil-lev.zip
            release/AT-GP-fil-lev.zip
            release/DisplayCombo.zip
          body_path: repo/CREDITS.md
